### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by btknorr** [component/s3#7]
I have cors configured correctly for my s3 bucket, but when I run the test code (with config setup correctly), I always get the following error:

XMLHttpRequest cannot load https://kaleida-images.s3.amazonaws.com/. The request was redirected to 'https://kaleida-images.s3-us-west-2.amazonaws.com/', which is disallowed for cross-origin requests that require preflight.

Please advise on what I need to do to make this work.  Thanks,

Brian

**Comment by DavyCode** [comment]
I am using AWS sdk for uploads, after spending some time searching online i stumbled upon this thread. thanks to @lsimoneau [45581857](https://github.com/component/s3/issues/7#issuecomment-45581857) its turns out the exact same thing was happening. I simply pointed my request Url to the region on my bucket by attaching the region property and it worked.

const s3 = new AWS.S3({
  accessKeyId: config.awsAccessKeyID,
  secretAccessKey: config.awsSecretAccessKey,
  region: 'eu-west-2'  // add region here
});

**Comment by loganpowell** [comment]
> The reason his happens (and also the reason why it self-resolves), is that when you set up an S3 bucket, there's a certain time during which the global bucket URL is not available, so AWS redirects to the region-specific URL. From the documentation:
> 
> > Temporary redirects automatically redirect users who do not have DNS information for the requested bucket. This occurs because DNS changes take time to propagate through the Internet. For example, if a user creates a bucket with a location constraint and immediately stores an object in the bucket, information about the bucket might not yet have been distributed throughout the Internet. Because the bucket is a subdomain of s3.amazonaws.com, Amazon S3 redirects it to the correct Amazon S3 location.
> 
> The redirect response that Amazon sends back when you request the global URL doesn't have CORS headers, so requests will fail until the DNS has propagated.

jesus christ, this has been driving me crazy (using terraform). Thank you @lsimoneau. You have saved my sanity.

**Comment by loganpowell** [comment]
for anyone else that stumbles across this, here's the setup that enables CORS to work with presigned urls, right out of the box (new s3 bucket, no waiting for DNS resolution:

```python
import boto3
from botocore.utils import fix_s3_host
from botocore.client import Config

AWS_REGION = os.environ.get("AWS_REGION")

if IS_LOCAL:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    s3 = boto3.client(
        "s3",
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_REGION,                          # <-- 👀

        config=Config(
            signature_version="v4",                      # <-- 👀
            s3 = {
                "addressing_style": "path"               # <-- 👀
            }
        )
    )
else:
    s3 = boto3.client(
        "s3",
        region_name=AWS_REGION,                          # <-- 👀
        config=Config(
            signature_version="v4",                      # <-- 👀
            s3 = {
                "addressing_style": "path"               # <-- 👀
            }
        )
    )

s3.meta.events.unregister("before-sign.s3", fix_s3_host) # <-- 👀
```
